### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by nishaq503** [maki-nage/distogram#4]
I found this excellent repo to use with some work I'm doing with very large images.

I see some places where loops could be replaced with list comprehensions or with some built-in methods in Python. I expect this would help improve performance by quite a bit. Would you be open to a PR with such performance-related changes?

**Comment by MainRo** [comment]
sure!
I tried to balance the performance and the readability of the code. If you see improvements feel free to submit a PR.

**Comment by nishaq503** [comment]
So far I'm seeing an improvement of ~18% in the runtime of the `update` function, which I think is the most important and time-consuming function here. I'll have the PR ready in a day or two. I am currently trying to properly organized the commits.

I was wondering, is there a way to insert a batch of values and then call `trim`/`trim_in_place` only once per batch? I realize that this would widen the error bounds from the paper but it might be a lot faster for a large distribution.

**Comment by MainRo** [comment]
Nice. Yes *update* is the bottleneck because in most use-cases it is called orders of magnitudes more than the other ones.

I did not look at feeding data with batches or micro-batches because the intent is to use this library with streaming data. In this way of working [micro]batching data is complex. So for now I would prefer to stick with a pure streaming way of working.

**Comment by MainRo** [comment]
merged in #5
